### ISSUE TITLE
Cannot add Locations of differing worlds

### ISSUE THREAD

**Issue by TaiwanTorchRz** [joehot200/AntiAura#122]
[18:34:28 WARN]: [AntiAura] Plugin AntiAura v11.86-1 generated an exception while executing task 1567
java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
        at org.bukkit.Location.subtract(Location.java:412) ~[patched_1.16.1.jar:git-Paper-135]
        at joehot200.D.a(D.java:354) ~[?:?]
        at joehot200.D.a(D.java:330) ~[?:?]
        at joehot200.aE.run(aE.java:221) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-135]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-135]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by joehot200** [comment]
Thanks, fixed for 11.87. Cant remember if fixed in the dev build yet.

**Comment by dodofan** [comment]
You really need to look at Discord more @joehot200. I discussed it with the OP there.
