### ISSUE TITLE
Chunk getEntities call error

### ISSUE THREAD

**Issue by djchewmacca** [joehot200/AntiAura#166]
Not sure if this is related to AntiAura or Protocollib but I have been getting a lot of spam in the console.
I am running the latest version of AntiAura 11.98 alongside Protocollib dev build 531.  I have used the stable version of ProtocolLib but it does the same.

This is the error messages I am getting....  Thanks

[11:41:37] [Netty Epoll Server IO #1/FATAL]: Thread Netty Epoll Server IO #1 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) [patched_1.17.1.jar:git-Paper-257]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2287) [patched_1.17.1.jar:git-Paper-257]
	at net.minecraft.server.level.WorldServer.b(WorldServer.java:1724) [patched_1.17.1.jar:git-Paper-257]
	at jdk.internal.reflect.GeneratedMethodAccessor130.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:240) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at joehot200.G.b(G.java:115) [AntiAura.jar:?]
	at joehot200.m.onPacketReceiving(m.java:1653) [AntiAura.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-257]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[11:41:38] [Netty Epoll Server IO #1/FATAL]: Thread Netty Epoll Server IO #1 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) [patched_1.17.1.jar:git-Paper-257]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2287) [patched_1.17.1.jar:git-Paper-257]
	at net.minecraft.server.level.WorldServer.b(WorldServer.java:1724) [patched_1.17.1.jar:git-Paper-257]
	at jdk.internal.reflect.GeneratedMethodAccessor130.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:240) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at joehot200.G.b(G.java:115) [AntiAura.jar:?]
	at joehot200.m.onPacketReceiving(m.java:1653) [AntiAura.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-257]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-257]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by joehot200** [comment]
Thanks for the bug report! Believe now fixed for AntiAura 11.99.

**Comment by djchewmacca** [comment]
Have you released the updated version? Can't seem to find it on the Spigot site. Thanks

**Comment by joehot200** [comment]
> Have you released the updated version? Can't seem to find it on the Spigot site. Thanks

Update will be coming tomorrow! Sorry for the wait.

**Comment by djchewmacca** [comment]
Thank you.
