### ISSUE TITLE
11.79: "[G]enerated an exception while executing task 14

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#42]
**Screenshot (or a video recording):** See additional details for the warning.

**AntiAura version:** 11.79

**Server version:** Paper version git-Paper-284 (MC: 1.15.2)

**Detailed description of the issue:**
Unsure.

**Additional details:**
[WARNING] [AntiAura] Plugin AntiAura v11.79 generated an exception while executing task 14
java.lang.IllegalArgumentException: Cannot add Locations of differing worlds
at org.bukkit.Location.subtract(Location.java:412) ~[patched_1.15.2.jar:git-Paper-284]
at joehot200.y.a(y.java:271) ~[?:?]
at joehot200.y.a(y.java:253) ~[?:?]
at joehot200.av.run(av.java:140) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-284]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-284]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-284]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by joehot200** [comment]
Fixed for 11.8
