### ISSUE TITLE
11.82: Task #20 generated an exception

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#66]
**Stacktrace:**
[22:33:27 WARN]: [AntiAura] Task #20 for AntiAura v11.82 generated an exception
java.lang.ClassCastException: class org.bukkit.configuration.MemorySection cannot be cast to class java.lang.String (org.bukkit.configuration.MemorySection is in unnamed module of loader java.net.URLClassLoader @34b7bfc0; java.lang.String is in module java.base of loader 'bootstrap')
        at joehot200.B.c(B.java:277) ~[?:?]
        at joehot200.B.b(B.java:231) ~[?:?]
        at joehot200.aB.a(aB.java:2868) ~[?:?]
        at joehot200.aB.a(aB.java:2735) ~[?:?]
        at joehot200.aB.d(aB.java:7380) ~[?:?]
        at joehot200.aB.c(aB.java:7353) ~[?:?]
        at joehot200.aT.run(aT.java:985) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.lang.Thread.run(Thread.java:834) [?:?]

**Server version:** Paper 1.8.8

**Comment by joehot200** [comment]
I think there is an error in your Violations section of the config somewhere, and that is causing these errors.

**Comment by ghost** [comment]
What error would that be? All I did was delete the violation commands for 2 and 5 completely, so it looks like this

2:
5:

**Comment by joehot200** [comment]
You must delete it entirely or leave it as a #  

Give it a go, see if it fixes the issue
